# Permissions

all: &all
  allowed_user_ids:
    - abc123
    - def456
  # Uncomment section below if you want to use affils
  # allowed_user_affils:
  #   - CUL_dpts-ldpd

development: *all
test: *all
